;//Alias header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2011-03-21 17:05:30

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

IDH_1000=如何开始？\如何开始.html	; 如何开始
IDH_1005=销售商品\销售.html	; 进行销售
IDH_1006=销退处理\销退.html	; 进行销售退货
IDH_1004=进行库存盘点\盘点.html	; 进行库存盘点
IDH_1001=查看报表\年度报表.html	; 年度报表
IDH_1002=查看报表\年度报表2.html	; 年度详细报表
IDH_1003=查看报表\年度报表23.html	; 员工销售统计
