;//Map header file for CHM project
;//Automatically generated by Easy CHM.
;//Website : http://www.zipghost.com
;//Email   : webmaster@zipghost.com
;//Date    : 2011-03-21 17:05:30

;//NOTE:
;//All strings after the ";" are commnets, they will be ignored by the CHM Compiler.

#define IDH_1000	1000	; 如何开始 如何开始？\如何开始.html
#define IDH_1005	1005	; 进行销售 销售商品\销售.html
#define IDH_1006	1006	; 进行销售退货 销退处理\销退.html
#define IDH_1004	1004	; 进行库存盘点 进行库存盘点\盘点.html
#define IDH_1001	1001	; 年度报表 查看报表\年度报表.html
#define IDH_1002	1002	; 年度详细报表 查看报表\年度报表2.html
#define IDH_1003	1003	; 员工销售统计 查看报表\年度报表23.html
